In [33]:
%pip install pandas openpyxl

Requirement already satisfied: pandas in ./.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: openpyxl in ./.venv/lib/python3.10/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.10/site-packages (from pandas) (2026.5)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.10/site-packages (from pandas) (2026.5)
Requirement already satisfied: et-xmlfile in ./.venv/lib/python3.10/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [34]:
from slot_util import load_slot_tables, print_df_attrs, get_reel_symbols, \
    get_reelstop_df, add_wild_combination_counts, add_scatter_window_counts, get_line_pattern_df, add_line_rtp, \
    get_fg_trigger_analysis

## Base Game

In [35]:
reel_df, paytable_df, free_spins_df, game_settings = load_slot_tables("sheet/FG.xlsx")

In [36]:
print_df_attrs(reel_df)
display(reel_df)

print_df_attrs(paytable_df)
display(paytable_df)

print_df_attrs(free_spins_df)
display(free_spins_df)

print_df_attrs(game_settings)
display(game_settings)

shape: (20, 5)
表: 滾輪表
列: Stop 索引
行: 第幾個滾輪

    R1  R2  R3  R4  R5
0    K   W   W   W   W
1    Q   K   K   K   K
2    J   Q   Q   Q   Q
3   10   J   J   J   J
4    9  10  10  10  10
5    9   9   9   9   9
6    S   S   S   S   S
7    Q   K   K   K   K
8    J   Q   Q   Q   Q
9   10   J   J   J   J
10   9  10  10  10  10
11  10   9   9   9   9
12   Q   K   K   K   K
13   J   Q   Q   Q   Q
14  10   J   J   J   J
15   9  10  10  10  10
16   9   9   9   9   9
17   J   J   J   J   J
18  10   J  10  10  10
19   9   9   9   9   9

shape: (6, 3)
表: 賠率表
列: 連線的 Symbol
行: 由左到右的連線數

        3   4    5
Symbol
K       5  30  100
Q       5  25  100
J       5  20   75
10      5  20   75
9       5  10   50
S       2   2    2

shape: (1, 3)
表: 免費遊戲次數表
列: Scatter Symbol
行: Scatter 數量

         3   4   5
Symbol
S       10  15  20

shape: (1,)
表: 遊戲設定
列: 設定名稱
值: 設定值

Setting
WindowHeight    3
Name: Value, dtype: int64

In [37]:
symbols = get_reel_symbols(reel_df)
symbols

['W', 'K', 'Q', 'J', '10', '9', 'S']

In [38]:
reelstop_df = get_reelstop_df(reel_df, symbols)

In [39]:
add_wild_combination_counts(reelstop_df, symbols)
add_scatter_window_counts(reelstop_df, window_height=game_settings["WindowHeight"])

In [40]:
print_df_attrs(reelstop_df)
display(reelstop_df)

shape: (20, 5)
表: Symbol 在各滾輪的 Stop 數
列: Symbol
行: 第幾個滾輪

        R1  R2  R3  R4  R5
Symbol
W        0   1   1   1   1
K        1   3   3   3   3
Q        3   3   3   3   3
J        4   5   4   4   4
10       5   3   4   4   4
9        6   4   4   4   4
S        1   1   1   1   1
-       20  20  20  20  20
WK       1   4   4   4   4
WQ       3   4   4   4   4
WJ       4   6   5   5   5
W10      5   4   5   5   5
W9       6   5   5   5   5
X_WK    19  16  16  16  16
X_WQ    17  16  16  16  16
X_WJ    16  14  15  15  15
X_W10   15  16  15  15  15
X_W9    14  15  15  15  15
3S       3   3   3   3   3
X_3S    17  17  17  17  17

In [41]:
line_df = get_line_pattern_df(reel_df, paytable_df, symbols, free_spins_df)
add_line_rtp(line_df, reelstop_df, paytable_df)

In [42]:
print_df_attrs(line_df)
display(
    line_df.style.format({
        "RTP": "{:.2%}",
    })
)

shape: (31, 15)
表: 連線與 Scatter 組合
列: Symbol x MatchCount

## Free Game

In [43]:
reel_fg_df, paytable_df, free_spins_df, _ = load_slot_tables("sheet/FG.xlsx", reel_sheet="Reel_FG")

In [44]:
print_df_attrs(reel_fg_df)
display(reel_fg_df)

print_df_attrs(paytable_df)
display(paytable_df)

print_df_attrs(free_spins_df)
display(free_spins_df)

shape: (20, 5)
表: 滾輪表
列: Stop 索引
行: 第幾個滾輪

    R1  R2  R3  R4  R5
0    K   W   W   W   W
1    Q   K   K   K   K
2    J   Q   Q   Q   Q
3   10   J   J   J   J
4    9  10  10  10  10
5    9   9   9   9   9
6    S   S   S   S   S
7    Q   K   K   K   K
8    J   Q   Q   Q   Q
9   10   J   J   J   J
10   9  10  10  10  10
11  10   9   9   9   9
12   Q   K   K   K   K
13   J   W   W   W   W
14  10   J   J   J   J
15   9  10  10  10  10
16   9   9   9   9   9
17   J   J   J   J   J
18  10   J  10  10  10
19   9   9   9   9

shape: (6, 3)
表: 賠率表
列: 連線的 Symbol
行: 由左到右的連線數

        3   4    5
Symbol
K       5  30  100
Q       5  25  100
J       5  20   75
10      5  20   75
9       5  10   50
S       2   2    2

shape: (1, 3)
表: 免費遊戲次數表
列: Scatter Symbol
行: Scatter 數量

         3   4   5
Symbol
S       10  15  20

In [45]:
symbols_fg = get_reel_symbols(reel_fg_df)
symbols_fg

['W', 'K', 'Q', 'J', '10', '9', 'S']

In [46]:
reelstop_fg_df = get_reelstop_df(reel_fg_df, symbols_fg)

In [47]:
add_wild_combination_counts(reelstop_fg_df, symbols_fg)
add_scatter_window_counts(reelstop_fg_df, window_height=game_settings["WindowHeight"])

In [48]:
print_df_attrs(reelstop_fg_df)
display(reelstop_fg_df)

shape: (20, 5)
表: Symbol 在各滾輪的 Stop 數
列: Symbol
行: 第幾個滾輪

        R1  R2  R3  R4  R5
Symbol
W        0   2   2   2   2
K        1   3   3   3   3
Q        3   2   2   2   2
J        4   5   4   4   4
10       5   3   4   4   4
9        6   4   4   4   3
S        1   1   1   1   1
-       20  20  20  20  19
WK       1   5   5   5   5
WQ       3   4   4   4   4
WJ       4   7   6   6   6
W10      5   5   6   6   6
W9       6   6   6   6   5
X_WK    19  15  15  15  14
X_WQ    17  16  16  16  15
X_WJ    16  13  14  14  13
X_W10   15  15  14  14  13
X_W9    14  14  14  14  14
3S       3   3   3   3   3
X_3S    17  17  17  17  16

In [49]:
line_fg_df = get_line_pattern_df(reel_fg_df, paytable_df, symbols_fg, free_spins_df)
add_line_rtp(line_fg_df, reelstop_fg_df, paytable_df)

In [50]:
print_df_attrs(line_fg_df)
display(
    line_fg_df.style.format({
        "RTP": "{:.2%}",
    })
)

shape: (31, 15)
表: 連線與 Scatter 組合
列: Symbol x MatchCount

## RTP

In [51]:
fg_trigger_df, fg_trigger_summary = get_fg_trigger_analysis(line_df, line_fg_df, free_spins_df)

In [52]:
print_df_attrs(fg_trigger_df)
display(fg_trigger_df)

print_df_attrs(fg_trigger_summary)
display(fg_trigger_summary)

shape: (3, 8)
表: 免費遊戲觸發分析
列: Scatter 數量
行.MatchCount: Scatter 數量 j
行.BaseProb: q_j：Base spin 出現 j 個 Scatter 的機率
行.InitialSpins: t_j：初次觸發給予的免費遊戲次數
行.FGProb: p_j：FG spin 出現 j 個 Scatter 的機率
行.RetriggerSpins: s_j：再次觸發給予的免費遊戲次數
行.RetriggerContribution: p_j s_j
行.AverageSpinsPerTrigger: t_j X
行.SpinsPerBaseSpin: Y_j = q_j t_j X

,MatchCount,BaseProb,InitialSpins,FGProb,RetriggerSpins,RetriggerContribution,AverageSpinsPerTrigger,SpinsPerBaseSpin
0,3,0.024384,10,0.025064,10,0.250638,14.001861,0.341427
1,4,0.002152,15,0.002238,15,0.033572,21.002791,0.045189
2,5,0.000076,20,0.000080,20,0.001599,28.003722,0.002127

shape: (4,)
表: 免費遊戲觸發摘要
ExpectedRetriggerSpins: Σ p_j s_j
SpinMultiplier: X = 1 / (1 - Σ p_j s_j)
InitialSpinsPerBaseSpin: Σ q_j t_j
TotalSpinsPerBaseSpin: Σ Y_j

ExpectedRetriggerSpins     0.285809
SpinMultiplier             1.400186
InitialSpinsPerBaseSpin    0.277636
TotalSpinsPerBaseSpin      0.388742
Name: Value, dtype: float64

In [53]:
base_rtp = line_df["RTP"].sum()
print(f'Base RTP: {base_rtp:.2%}')

fg_rtp = line_fg_df["RTP"].sum()
print(f'FG RTP: {fg_rtp:.2%}')

fg_total_rtp = (
    fg_trigger_summary["TotalSpinsPerBaseSpin"]
    * fg_rtp
)
print(f'Total RTP: {base_rtp+fg_total_rtp:.2%}')

Base RTP: 65.00%
FG RTP: 102.28%
Total RTP: 104.76%